### ISSUE TITLE
license

### ISSUE THREAD

**Issue by 3socha** [theoremoon/ShellgeiBot#27]
@theoldmoon0602 
良かったら、このリポジトリのライセンスを示しておいてほしいなと思います。

**Comment by theoremoon** [comment]
これはご丁寧にありがとうございます。 :bow: ちょっと手が離せないので2,3日ほったらかします

**Comment by theoremoon** [comment]
これ勝手にcloseにならないんですか？ #29 で解決したのでcloseしますね

**Comment by 3socha** [comment]
@theoldmoon0602 ありがとうございます :pray:
PR のコメントに `fix` とか `close` とか `resoleve` とかのキーワードと #Issue 番号を書いておくと、PR をマージした時に自動的に Issue が閉じられるようです。
https://help.github.com/en/articles/closing-issues-using-keywords
