### ISSUE TITLE
タグの削除

### ISSUE THREAD

**Issue by jiro4989** [theoremoon/ShellgeiBot#34]
https://twitter.com/theoldmoon0602/status/1151409190935470080

次郎がやってみようと思います。

https://github.com/theoldmoon0602/ShellgeiBot/blob/8272fbbdd9b6897652c074dbb8ff5932459cd662/tweet.go#L68-L78

**Comment by jiro4989** [comment]
@theoldmoon0602 
すみません。こちらで外部ファイルからタグ情報を取得していると思うのですが、
https://github.com/theoldmoon0602/ShellgeiBot/blob/68b61c93f39e21b95812eff2d5e5e5edd4ed8363/main.go#L97

BotConfig.Tagsには実際にはどういう値が入っていますか？
細かい目にテストを書きたいのでご共有いただけますでしょうか。
https://github.com/theoldmoon0602/ShellgeiBot/blob/68b61c93f39e21b95812eff2d5e5e5edd4ed8363/shellgei.go#L30-L37

**Comment by theoremoon** [comment]
`["シェル芸", "ゆるシェル"]`のような感じです

**Comment by jiro4989** [comment]
ありがとうございます。助かります

**Comment by theoremoon** [comment]
#35 でおそらく解決したのでclose
