### ISSUE TITLE
実行時間の制限が厳しくなった？

### ISSUE THREAD

**Issue by eggplants** [theoremoon/ShellgeiBot#61]
これは体感なのですが、以前は実行時間制約的に実行できていたような処理が実行/投稿されなくなったように感じます。
制約の仕様やサーバスペックが変更されたのであれば教えていただきたいです。
例: 投稿されなかったもの
```bash
unko.king 10|sed s/^　*//g>_
eval '<_ rb -l "\$_=?＞*'{{0..10},{10..0}}'+_1.chomp";'|egrep -o '^.{,10}'|textimg -asl10 -d1
```

**Comment by theoremoon** [comment]
実行時間の制限は変えてないですが、ランタイムをgVisorに差し替えたのでコンテナ自体の起動やシステムコールにかかる時間が伸びているのだと思います。影響が出ているようなのでタイムアウトを調整してみます

2020年11月24日(火) 19:51 haruna <notifications@github.com>:

**Comment by theoremoon** [comment]
タイムアウトを20secにしてみていますがどうでしょう？

**Comment by eggplants** [comment]
https://twitter.com/minyoruminyon/status/1331470510652153858
実行されましたね…ありがとうございます
