### ISSUE TITLE
textimgが実行されない

### ISSUE THREAD

**Issue by eggplants** [theoremoon/ShellgeiBot#62]
処理が重くtimeoutしているのか、少し前からShellgeiBotで実行されません。
`textimg あ -s`さえも通りません。
https://twitter.com/egpl0/status/1363000454003576843

**Comment by eggplants** [comment]
どうやら画像出力が死んだみたいです。
https://twitter.com/egpl0/status/1363001991635496963

**Comment by theoremoon** [comment]
報告ありがとうございました！　シェル芸botのhostでbashのdocker imageが消失していて、image抽出してくるような処理が失敗していたようです（それがなぜかはわかりませんが……）。いまは直りました！

https://twitter.com/minyoruminyon/status/1363308293003780096
