### ISSUE TITLE
リンクを考慮した文字数カウントと切り詰め

### ISSUE THREAD

**Issue by eggplants** [theoremoon/ShellgeiBot#63]
Tweet上限は280byteです。

```
http://xn--6iiaaaaaaaaaara16ixzav0b5c5lc.xn--6ii
http://xn--6iiaaaaaaah5d5e6cug4r86aj3atpnrla.xn--6ii
http://xn--6iiaaaaaaaaaaa6h6d7g6a15wma31g.xn--6ii
http://xn--6ii7c6wjbtt8s1ezbzaaaaaaaaaf.xn--6ii
http://xn--6iia0pqaa9n5a41cxhld6a97caaaaaaa.xn--6ii
http://xn--6iiaad3jnb1oq4bopibbabaaaaaa.xn--6ii
http://xn--6iiaaaaaaag3vwaa18ba49bl2f4dda.xn--6ii
http://xn--6iiaaaaaaaaaaaaa4zxcs4aibye.xn--6ii

```

は397byteですが、Twitter上では短縮され`https://t.co/xxxxxxxxxx`となるので、`(13byte+改行1byte)*8=112byte`となり切り詰めなくて良くなります。

正直必要ないかもしれませんが、この仕様があると<https://twitter.com/minyoruminyon/status/1378568884786110465?s=19>のようなツイートがうまくいくようになります。

**Comment by theoremoon** [comment]
これやりたいですけど、 https://github.com/twitter/twitter-text/ 相当のものが必要になるんですよね

**Comment by eggplants** [comment]
Go実装を待つ感じですね
